export const TURN_STATES = {
  IDLE: "IDLE",
  FIRST_ACTION: "FIRST_ACTION",
  WAITING_ACTION: "WAITING_ACTION",
  SECOND_ACTION: "SECOND_ACTION",
  WAITING: "WAITING",
  DETERMINE_KO: "DETERMINE_KO",
  END: "END",
};
