export const TILE_TYPES = {
  1: { walkable: true, encounter: true, terrain: "tallGrass" },
  2: { walkable: true, encounter: false, terrain: "ground" },
  3: { walkable: false, encounter: false, terrain: "solid" },
  4: {
    walkable: true,
    encounter: true,
    terrain: "water",
    surfable: true,
    sin: true,
  },
  5: {
    walkable: false,
    encounter: true,
    terrain: "borderWater",
    surfable: true,
    sin: true,
  },
  6: {
    walkable: true,
    encounter: false,
    terrain: "ground",
    trigger: "door",
    warp: false,
  },
  7: {
    walkable: true,
    encounter: false,
    terrain: "ground",
    trigger: "door",
    warp: true,
  },
  8: {
    walkable: false,
    encounter: false,
    terrain: "cliff_down",
    direction: "down",
    surfable: false,
  },
  9: {
    walkable: true,
    encounter: false,
    terrain: "ground",
    trigger: "changeMap",
    warp: true,
  },
};
