import { GROWTH_RATES_DATABASE } from "../../experience/growthRates/growthRates.database.js";
import { MOVES_DATABASE } from "../../moves/moves.database.js";

export const CHARMELEON_SPECIES = {
  id: "charmeleon",
  pokedexId: "005",
  name: "REPTINCEL",
  types: ["FIRE"],
  femaleRate: 50,
  catchRate: 45,
  growthRate: GROWTH_RATES_DATABASE.MEDIUM_SLOW,
  baseExp: 142,
  baseStats: {
    hp: 58,
    attack: 64,
    defense: 58,
    specialAtt: 80,
    specialDef: 65,
    speed: 80,
  },
  animations: {
    idle: {
      front: "charmeleon_front_idle",
      back: "charmeleon_back_idle",
    },
  },
  evolutions: [{ method: "level", level: 36, target: "charizard" }],
  learnset: {
    levelUp: [
      { level: 1, move: MOVES_DATABASE.scratch },
      { level: 1, move: MOVES_DATABASE.growl },
      { level: 17, move: MOVES_DATABASE.surf }, // 7
      { level: 13, move: "SMOKESCREEN" },
      { level: 20, move: "DRAGON_RAGE" },
      { level: 24, move: "SCARY_FACE" },
      { level: 30, move: "FIRE_FANG" },
      { level: 39, move: "FLAME_BURST" },
      { level: 46, move: "SLASH" },
      { level: 54, move: "FLAMETHROWER" },
      { level: 62, move: "FIRE_SPIN" },
      { level: 71, move: "INFERNO" },
    ],
    tmhm: [
      "Ultimapoing",
      "Danse Lames",
      "Ultimawashi",
      "Toxik",
      "Plaquage",
      "Bélier",
      "Damoclès",
      "Sacrifice",
      "Riposte",
      "Frappe Atlas",
      "Frénésie",
      "Draco-Rage",
      "Tunnel",
      "Copie",
      "Reflet",
      "Protection",
      "Patience",
      "Lance-Flammes",
      "Météores",
      "Coud'Krâne",
      "Repos",
      "Clonage",
      "Coupe",
      "Force",
    ],
  },
};
