import { createImg } from "../../../../../shareds/utils/assets/assets.utils.js";
export const PARTY_SLOT_CONFIG = {
  first: {
    positionX: 60,
    positionY: 15,
    width: 150,
    height: 22,
    image: createImg("game/assets/images/ui/party/party-slot.png"),
    imageHovered: createImg("game/assets/images/ui/party/party-slot-hover.png"),
    scale: 1.7,
  },
  second: {
    positionX: 60,
    positionY: 65,
    width: 150,
    height: 22,
    image: createImg("game/assets/images/ui/party/party-slot.png"),
    imageHovered: createImg("game/assets/images/ui/party/party-slot-hover.png"),
    scale: 1.7,
  },
  third: {
    positionX: 60,
    positionY: 115,
    width: 150,
    height: 22,
    image: createImg("game/assets/images/ui/party/party-slot.png"),
    imageHovered: createImg("game/assets/images/ui/party/party-slot-hover.png"),
    scale: 1.7,
  },
  fourth: {
    positionX: 60,
    positionY: 165,
    width: 150,
    height: 22,
    image: createImg("game/assets/images/ui/party/party-slot.png"),
    imageHovered: createImg("game/assets/images/ui/party/party-slot-hover.png"),
    scale: 1.7,
  },
  fifth: {
    positionX: 60,
    positionY: 215,
    width: 150,
    height: 22,
    image: createImg("game/assets/images/ui/party/party-slot.png"),
    imageHovered: createImg("game/assets/images/ui/party/party-slot-hover.png"),
    scale: 1.7,
  },
  sixth: {
    positionX: 60,
    positionY: 265,
    width: 150,
    height: 22,
    image: createImg("game/assets/images/ui/party/party-slot.png"),
    imageHovered: createImg("game/assets/images/ui/party/party-slot-hover.png"),
    scale: 1.7,
  },
};
