export const EXP_STATES = {
  IDLE: "IDLE",
  ANIMATING: "ANIMATING",
  LEVEL_UP: "LEVEL_UP",
  CHECK_LEARNSET: "CHECK_LEARNSET",
  CHOICE: "CHOICE",
  LEARN_MOVE: "LEARN_MOVE",
  LEARN_DIALOG: "LEARN_DIALOG",

  CHECK_EVOLUTION: "CHECK_EVOLUTION",
  EVOLUTION: "EVOLUTION",
  FINISHED: "FINISHED",
};
