export const BATTLE_RESULT_STATES = {
  IDLE: "IDLE",
  ANIMATING: "ANIMATING",
  LEVEL_UP: "LEVEL_UP",
  CHECK_LEARNSET: "CHECK_LEARNSET",
  LEARN_MOVE: "LEARN_MOVE",
  WANTS_TO_LEARN_DIALOG: "WANTS_TO_LEARN_DIALOG",
  REPLACE_MOVE_DIALOG: "REPLACE_MOVE_DIALOG",
  FINISH_REPLACE_MOVE_DIALOG: "FINISH_REPLACE_MOVE_DIALOG",
  CHECK_EVOLUTION: "CHECK_EVOLUTION",
  EVOLUTION: "EVOLUTION",
  FINISHED: "FINISHED",
};
