export const BATTLE_PHASES = {
  INTRO: "INTRO",
  PLAYER_THROW_POKEBALL: "PLAYER_THROW_POKEBALL",
  POKEMON_APPEARS: "POKEMON_APPEARS",
  BATTLE_MENU: "BATTLE_MENU",
  CATCH_POKEMON: "CATCH_POKEMON",
};
